spring:
  application:
    name: product-service
  cloud:
    config:
      uri: http://config-server-url:8084
      fail-fast: false  # Application won't fail if the config server is unavailable
      retry:
        max-attempts: 5  # Retry connection to the Config Server a few times
        initial-interval: 2000  # Initial retry delay in milliseconds
